name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      # Step 4: Run tests
      - name: Run tests
        run: pytest

      # Step 5: Build Docker image
      - name: Build Docker image
        run: docker build -t ajay123456789/midterm_assignment .

      # Step 6: Log in to Docker Hub
      - name: Log in to Docker Hub
        run: echo "Ajay@123456" | docker login -u "ajay123456789" --password-stdin

      # Step 7: Push Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: docker push ajay123456789/midterm_assignment
